title: Raymond Diaz # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Human Resource Manager 
  <br><br>
  Contact Information
  <br><br>
  Email: raymond.diaz1982@gmail.com<br><br>
  <a href="https://www.linkedin.com/in/raymond-diaz-5b6685185/">View My LinkedIn Profile</a><br>
  <a href="#">View My Video Biography</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
